### ISSUE TITLE
Verify HTML entity names

### ISSUE THREAD

**Issue by nathany** [threedaymonk/htmlentities#19]
While looking at that duplicate `inodot` key that was fixed in #17, I noticed the capital letter below is called `Iodot`. That seemed inconsistent with other capital letters, so I looked it up.

What I found was `&Idot;` without the o. That's a bit strange too.

I'm curious where this list of entities came from and if there is any way to verify that they are all correct?

**Comment by franklinyu** [comment]
@nathany I found that `htmlentities` has both: [Iodot](https://github.com/threedaymonk/htmlentities/blob/master/lib/htmlentities/mappings/expanded.rb#L470) (as you found) and [Idot](https://github.com/threedaymonk/htmlentities/blob/master/lib/htmlentities/mappings/expanded.rb#L448).

**Comment by nathany** [comment]
oh. thanks. ;-)
