### ISSUE TITLE
decode fails on html_safe strings

### ISSUE THREAD

**Issue by Mandaryn** [threedaymonk/htmlentities#20]
```
coder = HTMLEntities.new
string = "&eacute;lan"
coder.decode(string) # => "élan" 
coder.decode(string.html_safe) # => "lan"
```

**Comment by threedaymonk** [comment]
This looks like the same problem as #13 (specifically, [this problem](https://github.com/threedaymonk/htmlentities/issues/13#issuecomment-26914325)). In short, it's `ActiveSupport::SafeBuffer` that's at fault: it breaks `gsub`.

**Comment by Mandaryn** [comment]
thanks for quick replay, couldn't find a nice way to 'unsafe' string but #to_str seems to do the job
