### ISSUE TITLE
expanded.rb - warning: key "inodot" is duplicated and overwritten on line 466

### ISSUE THREAD

**Issue by denegny** [threedaymonk/htmlentities#27]
/gems/htmlentities-4.3.1/lib/htmlentities/mappings/expanded.rb:465: warning: key "inodot" is duplicated and overwritten on line 466

**Comment by wbrisett** [comment]
I noticed this as well. My script which uses htmlentities still works, but is producing this line along with the resulting files.

**Comment by threedaymonk** [comment]
@wbrisett This should have been fixed in version 4.3.3. Which version are you using?

**Comment by dmick** [comment]
me too, 4.3.1 through redmine

**Comment by sandstrom** [comment]
This can be closed, this issue is fixed in `4.3.3`
