### ISSUE TITLE
Using this with Controller

### ISSUE THREAD

**Issue by narutoniue** [threedaymonk/htmlentities#28]
I am new to Ruby.  I tried implementing the gem in my controller but it is not working.

    class linksController < ApplicationController
      require 'erb'
      include ERB::Util
      require 'open-uri'
      require 'htmlentities'

      def index
        coder = HTMLEntities.new
        @test = coder.encode('hdhdhd-shgssg- shsah', :basic, :decimal)
      end
    end

When I look at the source code, it is not being converted.

**Comment by threedaymonk** [comment]
What is your desired result in this case?

`encode` doesn't convert every codepoint to an entity, but only those that are (a) ASCII, but unsafe, or (b) are not ASCII. Non of the characters in your example fit those criteria.
