### ISSUE TITLE
Encoding for "μ" does not seem to work

### ISSUE THREAD

**Issue by MariusDanner** [threedaymonk/htmlentities#29]
Whenever I want to encode "μ" it results in "Ã\u0082Âµ" and not in "&mu;"

**Comment by threedaymonk** [comment]
I need more information than this. Can you write some code to reproduce the problem?

**Comment by MariusDanner** [comment]
```
coder = HTMLEntities.new
coder.decode(coder.encode("µ"))
=> "Ã\u0082Âµ"

```

I tried this with 
`coder = HTMLEntities.new(:expanded)`
and with several decoding options

**Comment by threedaymonk** [comment]
I can't reproduce your result. Tell me more about your environment: operating system, version of Ruby, shell encoding, etc.

**Comment by MariusDanner** [comment]
Ruby:
`ruby 2.1.1p76 (2014-02-24 revision 45161) [i686-linux]`
Rails:
`Rails 3.2.22.5`
OS:
`vagrant@precise32:/vagrant$ cat /proc/version `
`Linux version 3.2.0-23-generic-pae (buildd@palmer) (gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu4) ) #36-Ubuntu SMP Tue Apr 10 22:19:09 UTC `
`vagrant@precise32:/vagrant$ cat /etc/*-release`
`DISTRIB_ID=Ubuntu`
`DISTRIB_RELEASE=12.04`
`DISTRIB_CODENAME=precise`
`DISTRIB_DESCRIPTION="Ubuntu 12.04 LTS"`

character encoding:
`vagrant@precise32:/vagrant$ locale charmap`
`+ISO-8859-1`

Lang: 
`en_US`

**Comment by threedaymonk** [comment]
Ah. You'll need to be in UTF-8 encoding, not ISO-8859-1.

> HTMLEntities works with UTF-8 (or ASCII) strings only.

**Comment by MariusDanner** [comment]
Thank you very much.
